

services:
  drupal:
    image: drupal:9
    depends_on:
     - postgres-db
    volumes:
      - drupal-modules:/var/www/html/modules \
      - drupal-profiles:/var/www/html/profiles \
      - drupal-sites:/var/www/html/sites \
      - drupal-themes:/var/www/html/themes \
      -  drupal-data:/var/lib/postgresql/data
    ports:
      - 8080:80

  postgres-db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=pass


volumes:
   drupal-modules:
   drupal-profiles:
   drupal-sites:
   drupal-themes:
   drupal-data: